/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.apache.commons.io.FileUtils;
import org.sikuli.Sikuli;
import java.io.File;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void web(){
        System.out.println(new App().getGreeting());
        ChromeOptions options = new ChromeOptions();

        WebDriver driver = new ChromeDriver(options);
        driver.manage().window().maximize();

        driver.get("https://google.com");

        File scrFile = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
        try{
            FileUtils.copyFile(scrFile, new File("c:\\tmp\\screen.png"));
        }
        catch(Exception e){

        }
        finally{
            driver.quit();
        }
    }

    public static void nativeApp(){
        Sikuli.sikuliTest();
    }

    public static void main(String[] args) {
        // web();
        nativeApp();
    }
}
